version: '3'

services:
    
    jupyter:
        build: ./jupyter
        ports:
           - 8888:8888
        volumes:
           - ./public:/mnt
        links:
           - mongodb

    redis:
        image: redis:latest
        volumes:
           - redis-data:/data
        command: redis-server --appendonly yes
        environment:
           - TZ=Asia/Tokyo 

    get-search-result:
        build: ./get-search-result
        env_file: .env
        links:
           - redis

    collect:
        build: ./collect
        env_file: .env
        links:
           - mongodb
           - get-body
           - get-search-result
    
    get-body:
        build: ./get-body
        env_file: .env
        links:
           - redis

    analysis:
        build: ./analysis
        links:
           - mongodb

    mongodb:
        image: mongo:3.4.4
        restart: always
        volumes:
            - db-data:/data/db

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

